### ISSUE TITLE
do not expect dark background

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/forany#1]
I'm using a light background, and forany's yellow output '▻ Processing 4 of 24 directories failed.' is totally unreadable. 
either auto-detect the color scheme, or add a --light-bg option to reverse the coloring.

**Comment by goloroden** [comment]
Hi @stefanheine!

Thanks for providing this feature request!

I have taken a closer look at this, and I was not able to find a way to reliably detect the background color of the shell which works on all shells and operating systems. So, unfortunately, this does not seem possible.

I also thought about the option to slightly change colors, e.g. to something such as the [Solarized](http://ethanschoonover.com/solarized) theme, which should work equally well on dark and on light backgrounds. Unfortunately, this requires different colors than the default ones that are supported by each shell: And 256- or even 16M-color support is not available on all shells and operating systems. So, this would only be a solution for *some* systems, and it would require a lot of effort.

Since the underlying module [buntstift](https://github.com/thenativeweb/buntstift) uses the terminal's default colors, chances are that you will have the same problems with each other application that uses the default colors.

Hence I'd suggest to simply adjust the colors of the terminal, so that yellow becomes more readable on a light background. I think this is the best solution here: It works on each shell on each operating system, it at once improves readability for any other application as well, and it does not require any code changes.

So, I won't fix this issue, but politely ask you to adjust your color schema :-)
