### ISSUE TITLE
option to interpret 'git status' output

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/forany#3]
I would love to see an option that automatically parses the 'git status' output, to output only those directories that have outstanding work, and suppress those that just show "nothing to commit, working directory clean".

**Comment by goloroden** [comment]
The solution to this is two-fold:

First: The newly published version `0.5.0` of forany skips output of commands that do not return a result. So you get way less output if there is neither an error nor some output.

Second: I don't want to add special support for `git status` to forany, because this is out of scope for this tool. But you can do some bash magic, and get what you want.

If you run

```bash
$ forany 'if [[ -n $(git status -s 2>/dev/null) && $? -eq 0 ]]; then git status; fi'
```

you should get what you want. Please note that this bash call will omit errors, e.g. if a directory does not even contain a `.git` directory, you won't get an error here, but I'm pretty sure that one can improve this snippet to also support this :-)
